on:
  workflow_call:
    inputs:
      service_name:
        type: string
        description: 'Name of the service'
        required: true
      environment:
        type: string
        description: 'Environment to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - uses: actions/checkout@v4
      - name: Update kube config
        run: |
            aws eks update-kubeconfig --name eks-infra --region us-east-1  --kubeconfig ./kubeconfig
            echo 'KUBE_CONFIG_DATA<<EOF' >> $GITHUB_ENV
            echo $(cat ./kubeconfig | base64) >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
      - name: helm deploy
        uses: koslib/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: ${{ env.KUBE_CONFIG_DATA }}
        with:
          command: |
            helm repo add prosperi-charts https://zimran-tech.github.io/helm-charts
            helm repo update

            helm upgrade --install ${{ inputs.service_name }} prosperi-charts/app \
               --version 2.0.0 -f helm-values-staging.yaml \
               --set image=${{ steps.login-ecr.outputs.registry }}/${{ needs.build.outputs.IMAGE }} \
               -n prosperi-services-${{ inputs.environment }} --debug
